name: Docker Image CI

on:
   push:
     branches: 
       - master
   pull_request:
     branches: 
       - master   
   schedule:
     - cron: "0 2 ** 1-5"
  
jobs:

  build:

    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sum3dh/ospos:latest
      
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sum3dh/ospos:latest
      
  build:

    runs-on: macOS-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sum3dh/ospos:latest
